### ISSUE TITLE
The results are inconsistent with the paper.

### ISSUE THREAD

**Issue by ShenfeiPei** [syxiaa/ball-k-means#4]
I ran the algorithm on Epileptic with k=50, and the centers are read from Eplic3.csv. However, the number of calculating distances of the version of ring and no ring are 3.5E6 and 16.1E6 respectively, which is not consistent with the result shown in Table 3 in the paper.

**Comment by syxiaa** [comment]
Hello dear reader, I just checked your question.&nbsp;Your experimental results are correct, except that the scientific notation used in our paper only retains one digit.







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "syxiaa/ball-k-means"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月16日(星期六) 上午10:01
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[syxiaa/ball-k-means] The results are inconsistent with the paper. (Issue #4)





 
I ran the algorithm on Epileptic with k=50, and the centers are read from Eplic3.csv. However, the number of calculating distances of the version of ring and no ring are 3.5E6 and 16.1E6 respectively, which is not consistent with the result shown in Table 3 in the paper.

**Comment by ShenfeiPei** [comment]
I get it, thx for your reply.

**Comment by ShenfeiPei** [comment]
I get it, thx for your reply.
